# Generated by Django 2.2.6 on 2019-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=30)),
                ('items', models.TextField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costume_name', models.TextField(max_length=30)),
                ('costume_about', models.TextField(max_length=300)),
                ('costume_count', models.IntegerField()),
                ('costume_price', models.IntegerField()),
                ('costume_image', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
