# Generated by Django 2.2.6 on 2019-12-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume',
            name='costume_name',
            field=models.TextField(max_length=100),
        ),
    ]
