# Generated by Django 2.2.6 on 2019-11-29 01:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=30)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField(verbose_name=models.IntegerField(max_length=100))),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='costume',
            name='costume_image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
