# Generated by Django 2.2.6 on 2019-11-29 10:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191129_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
