# Generated by Django 2.2.6 on 2019-12-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191204_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costume',
            old_name='costume_about',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='costume',
            old_name='costume_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='costume',
            old_name='costume_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='costume',
            old_name='costume_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='costume',
            old_name='costume_price',
            new_name='price',
        ),
    ]
