# Generated by Django 2.2.6 on 2019-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191129_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.TextField(),
        ),
    ]
